name: zos
description: An experimental macOS launcher application
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: 1.7.0
  flutter_hooks: ^0.10.0
  hooks_riverpod: ^0.1.0
  flutter_svg:
  flutter_feather_icons: 1.0.3
  google_fonts: 1.0.0
  reorderables: 0.3.2

flutter:
  uses-material-design: true
  
  assets:
   - assets/images/


